// Types for starting test
export const START_TEST_REQUEST = 'START_TEST_REQUEST'
export const START_TEST_SUCCESS = 'START_TEST_SUCCESS'
export const START_TEST_FAIL = 'START_TEST_FAIL'

export const SAVE_TEST_RESULT_REQUEST = 'SAVE_TEST_RESULT_REQUEST'
export const SAVE_TEST_RESULT_SUCCESS = 'SAVE_TEST_RESULT_SUCCESS'
export const SAVE_TEST_RESULT_FAIL = 'SAVE_TEST_RESULT_FAIL'
